//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO_LIST
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string Title { get; set; }
        public bool IsActive { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> PriorityNo { get; set; }
        public int CategoriId { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
    }
}
